name: demo workflow
on: push
jobs:
  wish:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello Message
        run: echo "hello this is excuted on ubuntun runner"
      - name: new task
        run: touch 1.txt
      - name: adding txt to file
        run: echo "this is masater" > 1.txt
      - name: checking file permissions
        run: ls -lh 1.txt
      - name: read the file
        run: cat 1.txt
  python:
    runs-on: ubuntu-latest
    steps:
      - name: print im ok using python
        shell: python
        run: print("im ok, this line is printed using python")
  depended_job:
    runs-on: ubuntu-latest
    needs: [wish, python]
    steps:
      - name: this job runs after completion of 1st and 2nd job
        run: echo "date"
        