name: demo workflow
on: push
jobs:
  wish:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "hello world"
  pyhton-test:
    runs-on: ubuntu-latest
    steps:
      - name: use python shell
        run: |
          python3 -c "print('hello from python')"
  third-job:
    runs-on: ubuntu-latest
    needs: [wish, pyhton-test]
    steps:
      - name: final step
        run: echo "all jobs are done"
  print-my-secret:
    runs-on: ubuntu-latest
    needs: third-job
    steps:
      - name: print secret
        run: echo "my secret is ${{ secrets.MY_NAME }}"
        